version: "3.1"

services:
  django:
    container_name: "todo_django"
    restart: always
    command: gunicorn DjangoTodo.wsgi:application --bind=0.0.0.0:8000 --reload
    build: .
    volumes:
      - ./app/:/app

  nginx:
    container_name: "todo_nginx"
    depends_on:
      - django
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./app/DjangoTodo/static:/www/static
