# Generated by Django 2.2.1 on 2019-05-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date to be done')),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
